function crlf(lines: readonly string[]): Uint8Array {
  return Buffer.from(`${lines.join('\r\n')}\r\n`, 'utf8');
}

export const RFC5322_REPLY_WITH_ATTACHMENT = crlf([
  'From: Alice Example <alice@example.test>',
  'To: Chief Example <chief@example.test>',
  'Cc: Operations <ops@example.test>',
  'Date: Fri, 17 Jul 2026 12:00:00 +0000',
  'Message-ID: <reply-002@example.test>',
  'In-Reply-To: <root-001@example.test>',
  'References: <root-001@example.test>',
  'Subject: Re: Deterministic protocol fixture',
  'MIME-Version: 1.0',
  'Content-Type: multipart/mixed; boundary="chief-boundary-001"',
  '',
  '--chief-boundary-001',
  'Content-Type: text/plain; charset=utf-8',
  'Content-Transfer-Encoding: 7bit',
  '',
  'The protocol-shaped reply is deterministic.',
  '',
  '--chief-boundary-001',
  'Content-Type: text/plain; name="evidence.txt"',
  'Content-Disposition: attachment; filename="evidence.txt"',
  'Content-Transfer-Encoding: base64',
  '',
  'Ynl0ZS1leGFjdC1ldmlkZW5jZQo=',
  '--chief-boundary-001--',
]);

export const RFC3464_BOUNCE = crlf([
  'From: Mail Delivery System <mailer-daemon@example.test>',
  'To: Chief Example <chief@example.test>',
  'Date: Fri, 17 Jul 2026 12:01:00 +0000',
  'Message-ID: <dsn-003@example.test>',
  'Subject: Delivery Status Notification (Failure)',
  'MIME-Version: 1.0',
  'Content-Type: multipart/report; report-type=delivery-status; boundary="dsn-boundary-001"',
  '',
  '--dsn-boundary-001',
  'Content-Type: text/plain; charset=utf-8',
  '',
  'Delivery failed.',
  '--dsn-boundary-001',
  'Content-Type: message/delivery-status',
  '',
  'Reporting-MTA: dns; mx.example.test',
  'Original-Envelope-Id: operation-a',
  '',
  'Final-Recipient: rfc822; recipient@example.test',
  'Original-Recipient: rfc822; recipient@example.test',
  'Action: failed',
  'Status: 5.1.1',
  'Diagnostic-Code: smtp; 550 5.1.1 mailbox unavailable',
  '',
  '--dsn-boundary-001',
  'Content-Type: message/rfc822',
  '',
  'From: Chief Example <chief@example.test>',
  'To: recipient@example.test',
  'Message-ID: <operation-a@example.invalid>',
  'Subject: Deterministic outbound fixture',
  '',
  'Body',
  '--dsn-boundary-001--',
]);

export function smtpRenderedFixture(messageId: string): Uint8Array {
  return crlf([
    'From: Chief Example <chief@example.test>',
    'To: Recipient Example <recipient@example.test>',
    `Message-ID: ${messageId}`,
    'Date: Fri, 17 Jul 2026 12:00:00 +0000',
    'Subject: Deterministic outbound fixture',
    'MIME-Version: 1.0',
    'Content-Type: text/plain; charset=utf-8',
    'Content-Transfer-Encoding: 7bit',
    '',
    'Approved byte-exact payload.',
  ]);
}
